Multi arch support

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -55,13 +55,21 @@ runs:
         exit 0
         fi
         echo "atlas-installed=1" >> $GITHUB_OUTPUT
-
     - name: Install AtlasCLI
       if:  steps.check_path.outputs.atlas-installed == 0
       shell: bash
       run: |
-        tar -C /tmp -xzf /tmp/mongodb-atlas-cli_*_linux_x86_64.tar.gz
-        sudo mv /tmp/mongodb-atlas-cli_*_linux_x86_64/bin/atlas /usr/bin
+        if [ ${{ runner.arch }} = "ARM64" ]; then
+            ARCH="arm64"
+        elif [ ${{ runner.arch }} = "X64" ]; then
+            ARCH="x86_64"
+        else
+          echo "::error title=⛔ error hint::Support ARM64 and AMD64 Only"
+          exit 1
+        fi
+        
+        tar -C /tmp -xzf /tmp/mongodb-atlas-cli_*_linux_${ARCH}.tar.gz
+        sudo mv /tmp/mongodb-atlas-cli_*_linux_${ARCH}/bin/atlas /usr/bin
     - name: Check os and architecture
       shell: bash
       run: |
