Only support linux

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,6 +10,12 @@ inputs:
 runs:
   using: 'composite'
   steps:
+    - name: Check Runner OS
+      if: ${{ runner.os != 'Linux' }}
+      shell: bash
+      run: |
+        echo "::error title=⛔ error hint::Support Linux Only"
+        exit 1
     - name: Find latest tag
       if: -z "${{ inputs.version }}"
       uses: oprypin/find-latest-tag@v1
